/**
 * PDF Generation Utility
 * Generates downloadable PDF from assistant results
 */

import jsPDF from 'jspdf';
import { toast } from '@/components/ai/Toast';

export interface PDFMetadata {
  assistantType: string;
  model: string;
  generatedAt?: Date;
}

/**
 * Generates and downloads a PDF from assistant sections
 * @param sections - Record of section titles to content
 * @param metadata - Assistant metadata (type, model, timestamp)
 */
export function generatePDF(
  sections: Record<string, string>,
  metadata: PDFMetadata
): void {
  try {
    // Create new PDF document (A4 size, portrait)
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    // Page dimensions
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    const contentWidth = pageWidth - 2 * margin;
    let yPosition = margin;

    // Helper function to add text with wrapping
    const addText = (text: string, fontSize: number, isBold = false) => {
      doc.setFontSize(fontSize);
      if (isBold) {
        doc.setFont('helvetica', 'bold');
      } else {
        doc.setFont('helvetica', 'normal');
      }

      const lines = doc.splitTextToSize(text, contentWidth);

      // Check if we need a new page
      if (yPosition + lines.length * (fontSize * 0.35) > pageHeight - margin) {
        doc.addPage();
        yPosition = margin;
      }

      doc.text(lines, margin, yPosition);
      yPosition += lines.length * (fontSize * 0.35) + 3;
    };

    // Title
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(16, 185, 129); // Emerald color
    doc.text('KimuntuPro AI Assistant', margin, yPosition);
    yPosition += 10;

    // Metadata
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 100); // Gray
    doc.text(`Assistant: ${formatAssistantType(metadata.assistantType)}`, margin, yPosition);
    yPosition += 5;
    doc.text(`Model: ${metadata.model}`, margin, yPosition);
    yPosition += 5;

    const timestamp = metadata.generatedAt || new Date();
    doc.text(`Generated: ${timestamp.toLocaleString()}`, margin, yPosition);
    yPosition += 10;

    // Divider line
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, yPosition, pageWidth - margin, yPosition);
    yPosition += 10;

    // Reset text color for content
    doc.setTextColor(0, 0, 0);

    // Add sections
    Object.entries(sections).forEach(([title, content]) => {
      // Section title
      addText(title, 14, true);
      yPosition += 2;

      // Section content
      addText(content, 10, false);
      yPosition += 5;
    });

    // Footer on all pages
    const totalPages = doc.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.setFont('helvetica', 'normal');

      const footerText = `Page ${i} of ${totalPages} | Generated by KimuntuPro`;
      const footerWidth = doc.getTextWidth(footerText);
      doc.text(footerText, (pageWidth - footerWidth) / 2, pageHeight - 10);
    }

    // Generate filename
    const dateStr = new Date().toISOString().split('T')[0]; // YYYY-MM-DD
    const filename = `KimuntuPro_${metadata.assistantType}_${dateStr}.pdf`;

    // Save PDF
    doc.save(filename);

    toast.success('✓ PDF downloaded');
  } catch (error) {
    console.error('Failed to generate PDF:', error);
    toast.error('Failed to generate PDF');
  }
}

/**
 * Format assistant type for display
 */
function formatAssistantType(type: string): string {
  const typeMap: Record<string, string> = {
    streamlined_plan: 'Streamlined Business Plan',
    exec_summary: 'Executive Summary + Financials',
    market_analysis: 'Market Analysis',
  };

  return typeMap[type] || type;
}
