/**
 * Unit Tests for Website Generator (Phase 3)
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import { generateWebsite } from '../websiteGenerator.js';
import type { WizardInput } from '@kimuntupro/shared';

// Mock the ClaudeClient
vi.mock('../../llm/claudeClient.js', () => {
  return {
    ClaudeClient: vi.fn().mockImplementation(() => ({
      complete: vi.fn().mockResolvedValue({
        text: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Test Website</title>
</head>
<body>
  <h1>Welcome to Test Company</h1>
  <p>This is a test website generated by Claude.</p>
</body>
</html>`,
        tokensIn: 1500,
        tokensOut: 2500,
        model: 'claude-sonnet-4-5-20250929',
        latencyMs: 3000,
        costCents: 42,
      }),
    })),
  };
});

describe('Website Generator', () => {
  const mockWizardInput: WizardInput = {
    companyName: 'Test Company',
    tagline: 'Building the future',
    shortDescription: 'We create amazing software solutions',
    businessType: 'technology',
    targetAudience: 'Small businesses and startups',
    mainGoal: 'lead_generation',
    enabledSections: {
      about: true,
      services: true,
      contact: true,
    },
    theme: 'ocean',
    layoutStyle: 'modern',
    heroHeadline: 'Transform Your Business',
    heroSubheadline: 'With cutting-edge technology',
    primaryCtaText: 'Get Started Today',
    contactEmail: 'info@testcompany.com',
    contactPhone: '555-0123',
    location: 'San Francisco, CA',
    socialLinks: {
      facebook: 'https://facebook.com/testcompany',
      twitter: 'https://twitter.com/testcompany',
    },
    brandVoice: 'professional',
  };

  beforeEach(() => {
    vi.clearAllMocks();
  });

  describe('generateWebsite', () => {
    it('generates a complete website with all required fields', async () => {
      const result = await generateWebsite(mockWizardInput);

      expect(result).toBeDefined();
      expect(result.siteSpec).toBeDefined();
      expect(result.siteCode).toBeDefined();
      expect(result.metadata).toBeDefined();
    });

    it('returns valid site spec with branding information', async () => {
      const result = await generateWebsite(mockWizardInput);

      expect(result.siteSpec.branding.companyName).toBe('Test Company');
      expect(result.siteSpec.branding.tagline).toBe('Building the future');
      expect(result.siteSpec.branding.brandVoice).toBe('professional');
    });

    it('returns valid site spec with hero section', async () => {
      const result = await generateWebsite(mockWizardInput);

      expect(result.siteSpec.hero.headline).toBe('Transform Your Business');
      expect(result.siteSpec.hero.subheadline).toBe('With cutting-edge technology');
      expect(result.siteSpec.hero.ctaText).toBe('Get Started Today');
      expect(result.siteSpec.hero.ctaAction).toBe('lead_generation');
    });

    it('returns valid site spec with contact information', async () => {
      const result = await generateWebsite(mockWizardInput);

      expect(result.siteSpec.contact.email).toBe('info@testcompany.com');
      expect(result.siteSpec.contact.phone).toBe('555-0123');
      expect(result.siteSpec.contact.location).toBe('San Francisco, CA');
    });

    it('returns valid site spec with social links', async () => {
      const result = await generateWebsite(mockWizardInput);

      expect(result.siteSpec.social.facebook).toBe('https://facebook.com/testcompany');
      expect(result.siteSpec.social.twitter).toBe('https://twitter.com/testcompany');
    });

    it('includes enabled sections in site spec', async () => {
      const result = await generateWebsite(mockWizardInput);

      expect(result.siteSpec.sections.length).toBe(3);
      expect(result.siteSpec.sections.some(s => s.title === 'About')).toBe(true);
      expect(result.siteSpec.sections.some(s => s.title === 'Services')).toBe(true);
      expect(result.siteSpec.sections.some(s => s.title === 'Contact')).toBe(true);
    });

    it('assigns correct order to sections', async () => {
      const result = await generateWebsite(mockWizardInput);

      const sections = result.siteSpec.sections;
      expect(sections[0].order).toBe(0);
      expect(sections[1].order).toBe(1);
      expect(sections[2].order).toBe(2);
    });

    it('assigns unique IDs to sections', async () => {
      const result = await generateWebsite(mockWizardInput);

      const sections = result.siteSpec.sections;
      const ids = sections.map(s => s.id);
      const uniqueIds = new Set(ids);
      expect(uniqueIds.size).toBe(sections.length);
    });

    it('returns valid HTML code', async () => {
      const result = await generateWebsite(mockWizardInput);

      expect(result.siteCode).toContain('<!DOCTYPE html>');
      expect(result.siteCode).toContain('<html');
      expect(result.siteCode).toContain('</html>');
      expect(result.siteCode).toContain('<head>');
      expect(result.siteCode).toContain('</head>');
      expect(result.siteCode).toContain('<body>');
      expect(result.siteCode).toContain('</body>');
    });

    it('ensures DOCTYPE is present', async () => {
      const result = await generateWebsite(mockWizardInput);

      expect(result.siteCode.toLowerCase()).toContain('<!doctype html>');
    });

    it('includes generation metadata with all required fields', async () => {
      const result = await generateWebsite(mockWizardInput);

      expect(result.metadata.model).toBe('claude-sonnet-4-5-20250929');
      expect(result.metadata.tokensIn).toBe(1500);
      expect(result.metadata.tokensOut).toBe(2500);
      expect(result.metadata.tokensUsed).toBe(4000);
      expect(result.metadata.latencyMs).toBe(3000);
      expect(result.metadata.costCents).toBe(42);
      expect(result.metadata.generatedAt).toBeInstanceOf(Date);
    });

    it('calculates total tokens correctly', async () => {
      const result = await generateWebsite(mockWizardInput);

      expect(result.metadata.tokensUsed).toBe(
        result.metadata.tokensIn + result.metadata.tokensOut
      );
    });

    it('handles custom API key option', async () => {
      const result = await generateWebsite(mockWizardInput, {
        apiKey: 'custom-api-key',
      });

      expect(result).toBeDefined();
    });

    it('handles custom maxTokens option', async () => {
      const result = await generateWebsite(mockWizardInput, {
        maxTokens: 10000,
      });

      expect(result).toBeDefined();
    });

    it('handles minimal wizard input', async () => {
      const minimalInput: WizardInput = {
        companyName: 'Minimal Co',
        enabledSections: {
          about: true,
        },
        theme: 'ocean',
        layoutStyle: 'modern',
        businessType: 'other',
        mainGoal: 'contact',
        brandVoice: 'professional',
      };

      const result = await generateWebsite(minimalInput);

      expect(result.siteSpec.branding.companyName).toBe('Minimal Co');
      expect(result.siteSpec.sections.length).toBe(1);
    });

    it('sets default values for missing optional fields', async () => {
      const minimalInput: WizardInput = {
        enabledSections: {
          about: true,
        },
        theme: 'ocean',
        layoutStyle: 'modern',
        businessType: 'other',
        mainGoal: 'contact',
        brandVoice: 'professional',
      };

      const result = await generateWebsite(minimalInput);

      expect(result.siteSpec.branding.companyName).toBe('My Business');
      expect(result.siteSpec.branding.tagline).toBe('');
      expect(result.siteSpec.hero.headline).toContain('Our Business');
    });
  });

  describe('HTML Post-Processing', () => {
    it('removes markdown code fences if present', async () => {
      // Mock ClaudeClient to return HTML with code fences
      const { ClaudeClient } = await import('../../llm/claudeClient.js');
      (ClaudeClient as any).mockImplementationOnce(() => ({
        complete: vi.fn().mockResolvedValue({
          text: '```html\n<!DOCTYPE html>\n<html></html>\n```',
          tokensIn: 100,
          tokensOut: 200,
          model: 'claude-sonnet-4-5-20250929',
          latencyMs: 1000,
          costCents: 5,
        }),
      }));

      const result = await generateWebsite(mockWizardInput);

      expect(result.siteCode).not.toContain('```html');
      expect(result.siteCode).not.toContain('```');
      expect(result.siteCode).toContain('<!DOCTYPE html>');
    });

    it('adds DOCTYPE if missing', async () => {
      // Mock ClaudeClient to return HTML without DOCTYPE
      const { ClaudeClient } = await import('../../llm/claudeClient.js');
      (ClaudeClient as any).mockImplementationOnce(() => ({
        complete: vi.fn().mockResolvedValue({
          text: '<html><head></head><body></body></html>',
          tokensIn: 100,
          tokensOut: 200,
          model: 'claude-sonnet-4-5-20250929',
          latencyMs: 1000,
          costCents: 5,
        }),
      }));

      const result = await generateWebsite(mockWizardInput);

      expect(result.siteCode.toLowerCase()).toContain('<!doctype html>');
    });
  });

  describe('Meta Information', () => {
    it('sets page title from company name', async () => {
      const result = await generateWebsite(mockWizardInput);

      expect(result.siteSpec.meta.title).toBe('Test Company Website');
    });

    it('sets page description from short description', async () => {
      const result = await generateWebsite(mockWizardInput);

      expect(result.siteSpec.meta.description).toBe('We create amazing software solutions');
    });

    it('uses default description if not provided', async () => {
      const input: WizardInput = {
        companyName: 'Test Co',
        enabledSections: { about: true },
        theme: 'ocean',
        layoutStyle: 'modern',
        businessType: 'other',
        mainGoal: 'contact',
        brandVoice: 'professional',
      };

      const result = await generateWebsite(input);

      expect(result.siteSpec.meta.description).toContain('Professional website for Test Co');
    });
  });
});
