export const LEGAL_SERVICES = [
    {
        id: 'document-analyzer',
        icon: 'FileText',
        title: 'Document Analyzer',
        description: 'Upload any legal document and talk to an AI lawyer for instant analysis, risk spotting, and Q&A.',
        path: '/dashboard/legal/document-analyzer',
        color: 'indigo',
        badge: 'New',
    },
    {
        id: 'immigration',
        icon: 'Globe',
        title: 'Immigration Law',
        description: 'US and Canada visa, status, hearing prep, and pathway guidance.',
        path: '/dashboard/legal/immigration',
        color: 'blue',
        badge: 'New',
    },
    {
        id: 'contracts',
        icon: 'FileText',
        title: 'Contract Review',
        description: 'Spot clause risk, negotiation issues, and document red flags.',
        path: '/dashboard/legal/contracts',
        color: 'pink',
    },
    {
        id: 'business',
        icon: 'Briefcase',
        title: 'Business Law',
        description: 'Formation, governance, compliance, and commercial guidance.',
        path: '/dashboard/legal/business',
        color: 'amber',
    },
    {
        id: 'consumer',
        icon: 'Shield',
        title: 'Consumer Law',
        description: 'Fraud, warranties, debt collection, and consumer rights support.',
        path: '/dashboard/legal/consumer',
        color: 'emerald',
    },
    {
        id: 'family',
        icon: 'Users',
        title: 'Family Law',
        description: 'Divorce, custody, support, and family-process preparation.',
        path: '/dashboard/legal/family',
        color: 'purple',
        badge: 'Beta',
    },
    {
        id: 'employment',
        icon: 'BadgeDollarSign',
        title: 'Employment Law',
        description: 'Workplace rights, termination, pay disputes, and HR issues.',
        path: '/dashboard/legal/employment',
        color: 'teal',
        badge: 'Beta',
    },
    {
        id: 'litigation',
        icon: 'Gavel',
        title: 'Civil Litigation',
        description: 'Demand letters, dispute prep, mediation, and court workflow.',
        path: '/dashboard/legal/litigation',
        color: 'indigo',
        badge: 'Beta',
    },
    {
        id: 'criminal',
        icon: 'Scale',
        title: 'Criminal Law Research',
        description: 'Criminal-law issue spotting plus links into research and chat.',
        path: '/dashboard/legal/criminal',
        color: 'slate',
        badge: 'Research',
    },
];

export const LEGAL_ASSISTANTS = [
    {
        id: 'document-analyzer',
        title: 'Legal Document Analyzer',
        description: 'Upload any legal document — contract, filing, lease, will — and talk to an AI lawyer who analyzes it, flags risks, and answers your questions live.',
        path: '/dashboard/legal/document-analyzer',
        accentFrom: 'from-indigo-500',
        accentTo: 'to-violet-600',
        borderColor: 'indigo',
        buttonBg: 'bg-indigo-600 hover:bg-indigo-500',
        buttonShadow: 'shadow-indigo-600/30 hover:shadow-indigo-500/40',
        eyebrow: 'AI Avatar + Analysis',
    },
    {
        id: 'immigration',
        title: 'Immigration Law Assistant',
        description: 'Guidance on visas, work permits, permanent residence, citizenship, and immigration hearings.',
        path: '/dashboard/legal/immigration',
        accentFrom: 'from-blue-500',
        accentTo: 'to-indigo-600',
        borderColor: 'blue',
        buttonBg: 'bg-blue-600 hover:bg-blue-500',
        buttonShadow: 'shadow-blue-600/30 hover:shadow-blue-500/40',
        eyebrow: 'US + Canada',
    },
    {
        id: 'family',
        title: 'Family Law Assistant',
        description: 'Support for custody, parenting plans, separation, support, and court-prep checklists.',
        path: '/dashboard/legal/family',
        accentFrom: 'from-purple-500',
        accentTo: 'to-fuchsia-600',
        borderColor: 'purple',
        buttonBg: 'bg-purple-600 hover:bg-purple-500',
        buttonShadow: 'shadow-purple-600/30 hover:shadow-purple-500/40',
        eyebrow: 'Beta',
    },
    {
        id: 'business',
        title: 'Business Law Assistant',
        description: 'Guidance on formation, compliance, commercial operations, and regulatory readiness.',
        path: '/dashboard/legal/business',
        accentFrom: 'from-amber-500',
        accentTo: 'to-orange-500',
        borderColor: 'amber',
        buttonBg: 'bg-amber-600 hover:bg-amber-500',
        buttonShadow: 'shadow-amber-600/30 hover:shadow-amber-500/40',
        eyebrow: 'SMB Ready',
    },
    {
        id: 'contracts',
        title: 'Contract Law Assistant',
        description: 'Review agreements, flag clauses, and prepare negotiation questions before signing.',
        path: '/dashboard/legal/contracts',
        accentFrom: 'from-pink-500',
        accentTo: 'to-rose-500',
        borderColor: 'pink',
        buttonBg: 'bg-pink-600 hover:bg-pink-500',
        buttonShadow: 'shadow-pink-600/30 hover:shadow-pink-500/40',
        eyebrow: 'Document Review',
    },
    {
        id: 'consumer',
        title: 'Consumer Law Assistant',
        description: 'Help with chargebacks, scams, defective products, collections, and complaint strategy.',
        path: '/dashboard/legal/consumer',
        accentFrom: 'from-emerald-500',
        accentTo: 'to-teal-500',
        borderColor: 'emerald',
        buttonBg: 'bg-emerald-600 hover:bg-emerald-500',
        buttonShadow: 'shadow-emerald-600/30 hover:shadow-emerald-500/40',
        eyebrow: 'Protection',
    },
    {
        id: 'employment',
        title: 'Employment Law Assistant',
        description: 'Workplace-rights guidance for pay disputes, retaliation, discrimination, and leave questions.',
        path: '/dashboard/legal/employment',
        accentFrom: 'from-teal-500',
        accentTo: 'to-cyan-600',
        borderColor: 'teal',
        buttonBg: 'bg-teal-600 hover:bg-teal-500',
        buttonShadow: 'shadow-teal-600/30 hover:shadow-teal-500/40',
        eyebrow: 'Workplace',
    },
    {
        id: 'litigation',
        title: 'Civil Litigation Assistant',
        description: 'Issue-spotting for disputes, demand letters, mediation, filing stages, and case preparation.',
        path: '/dashboard/legal/litigation',
        accentFrom: 'from-indigo-500',
        accentTo: 'to-violet-600',
        borderColor: 'indigo',
        buttonBg: 'bg-indigo-600 hover:bg-indigo-500',
        buttonShadow: 'shadow-indigo-600/30 hover:shadow-indigo-500/40',
        eyebrow: 'Disputes',
    },
    {
        id: 'criminal',
        title: 'Criminal Law Research Assistant',
        description: 'Jump into criminal-law topic triage, comparative research, and the existing legal demo surfaces.',
        path: '/dashboard/legal/criminal',
        accentFrom: 'from-slate-600',
        accentTo: 'to-slate-800',
        borderColor: 'slate',
        buttonBg: 'bg-slate-700 hover:bg-slate-600',
        buttonShadow: 'shadow-slate-700/30 hover:shadow-slate-600/40',
        eyebrow: 'Research',
    },
];

export const LEGAL_AGENT_PAGES = {
    immigration: {
        id: 'immigration',
        title: 'Immigration Law Assistant',
        subtitle: 'Visa, hearing, and status-prep workflows for US and Canadian immigration questions.',
        theme: 'blue',
        badge: 'US + Canada',
        categories: [
            'Visa Types and Status Changes',
            'Work Permits and Employment Authorization',
            'Permanent Residence and Green Cards',
            'Citizenship and Naturalization',
            'Asylum, Refugee, and Hearing Preparation',
            'Travel, Inadmissibility, and Appeals',
        ],
        prompts: [
            'Compare H-1B and TN options for a software engineer.',
            'What documents should I organize before an asylum hearing?',
            'How do Express Entry and provincial nominations differ?',
        ],
    },
    family: {
        id: 'family',
        title: 'Family Law Assistant',
        subtitle: 'A preparation space for family-law questions, documents, timelines, and attorney handoff notes.',
        theme: 'purple',
        badge: 'Beta',
        categories: [
            'Custody and Parenting Plans',
            'Divorce and Separation Preparation',
            'Child and Spousal Support',
            'Protective Orders and Safety Planning',
            'Mediation and Family Court Checklists',
        ],
        prompts: [
            'What records should I gather before a custody consultation?',
            'How should I prepare questions for a support modification hearing?',
            'What usually belongs in a co-parenting plan draft?',
        ],
    },
    business: {
        id: 'business',
        title: 'Business Law Assistant',
        subtitle: 'Preparation help for formation, governance, compliance, contracts, and commercial operations.',
        theme: 'amber',
        badge: 'SMB Ready',
        categories: [
            'Entity Formation and Structure',
            'Corporate Governance and Compliance',
            'Commercial Contracts and Vendor Terms',
            'IP, Licensing, and Brand Protection',
            'Employment, Risk, and Regulatory Issues',
        ],
        prompts: [
            'What questions should I ask before choosing LLC vs corporation?',
            'How do I organize a compliance checklist for a new startup?',
            'Which contract terms usually matter most in a vendor agreement?',
        ],
    },
    contracts: {
        id: 'contracts',
        title: 'Contract Law Assistant',
        subtitle: 'A contract-focused workspace for review prep, issue spotting, and negotiation framing.',
        theme: 'pink',
        badge: 'Document Review',
        categories: [
            'Contract Formation and Enforceability',
            'Risk Clauses and Indemnities',
            'Payment, Renewal, and Termination Terms',
            'Negotiation Prep and Redlines',
            'Breach, Remedies, and Dispute Clauses',
        ],
        prompts: [
            'Which clauses should I flag before signing a service agreement?',
            'How do I compare termination for convenience vs cause?',
            'What are common risks in a one-sided indemnity clause?',
        ],
    },
    consumer: {
        id: 'consumer',
        title: 'Consumer Law Assistant',
        subtitle: 'Support for refund disputes, scams, debt collection, and complaint escalation prep.',
        theme: 'emerald',
        badge: 'Protection',
        categories: [
            'Defective Products and Warranties',
            'Debt Collection and Credit Disputes',
            'Fraud, Scams, and Chargebacks',
            'Unfair Practices and Refund Issues',
            'Complaint Letters and Agency Escalation',
        ],
        prompts: [
            'What should I include in a warranty dispute letter?',
            'How do I document a scam for a bank or agency complaint?',
            'What rights apply when collectors keep calling me at work?',
        ],
    },
    employment: {
        id: 'employment',
        title: 'Employment Law Assistant',
        subtitle: 'Guidance prep for workplace-rights issues before speaking with HR, agencies, or counsel.',
        theme: 'teal',
        badge: 'Workplace',
        categories: [
            'Wages, Overtime, and Misclassification',
            'Termination, Severance, and Retaliation',
            'Discrimination and Harassment Documentation',
            'Leave, Accommodation, and Disability Issues',
            'Workplace Policies and Complaint Prep',
        ],
        prompts: [
            'What timeline should I build before reporting retaliation?',
            'Which records help with an unpaid overtime claim?',
            'How do I prepare for an HR meeting about accommodation?',
        ],
    },
    litigation: {
        id: 'litigation',
        title: 'Civil Litigation Assistant',
        subtitle: 'A dispute-prep workspace for claims, evidence organization, mediation, and next-step planning.',
        theme: 'indigo',
        badge: 'Disputes',
        categories: [
            'Demand Letters and Pre-Suit Strategy',
            'Evidence and Timeline Organization',
            'Mediation and Settlement Preparation',
            'Small Claims and Civil Procedure Basics',
            'Case Handoff Notes for Counsel',
        ],
        prompts: [
            'What belongs in a clean demand-letter package?',
            'How should I organize exhibits for a contract dispute?',
            'What should I prepare before a mediation session?',
        ],
    },
    criminal: {
        id: 'criminal',
        title: 'Criminal Law Research Assistant',
        subtitle: 'Bridge into the product’s comparative criminal-law research and demo chat experience.',
        theme: 'slate',
        badge: 'Research',
        categories: [
            'Offense Comparisons',
            'Search and Seizure',
            'Bail and Pretrial Detention',
            'Defenses and Sentencing',
            'Research and Comparative Analysis',
        ],
        prompts: [
            'Compare theft laws in Canada vs the US.',
            'How does bail work in both jurisdictions?',
            'What is the difference between self-defense standards?',
        ],
        links: [
            { label: 'Open Criminal Research', path: '/research' },
            { label: 'Open Legal Chat Demo', path: '/chat' },
        ],
    },
};

const SERVICE_KEY_MAP = {
    'document-analyzer': { title: 'legal_svc_docAnalyzer_title', desc: 'legal_svc_docAnalyzer_desc' },
    'immigration':        { title: 'legal_svc_immigration_title', desc: 'legal_svc_immigration_desc' },
    'contracts':          { title: 'legal_svc_contracts_title',   desc: 'legal_svc_contracts_desc' },
    'business':           { title: 'legal_svc_business_title',    desc: 'legal_svc_business_desc' },
    'consumer':           { title: 'legal_svc_consumer_title',    desc: 'legal_svc_consumer_desc' },
    'family':             { title: 'legal_svc_family_title',      desc: 'legal_svc_family_desc' },
    'employment':         { title: 'legal_svc_employment_title',  desc: 'legal_svc_employment_desc' },
    'litigation':         { title: 'legal_svc_litigation_title',  desc: 'legal_svc_litigation_desc' },
    'criminal':           { title: 'legal_svc_criminal_title',    desc: 'legal_svc_criminal_desc' },
};

const ASSISTANT_KEY_MAP = {
    'document-analyzer': { title: 'legal_asst_docAnalyzer_title', desc: 'legal_asst_docAnalyzer_desc' },
    'immigration':        { title: 'legal_asst_immigration_title', desc: 'legal_asst_immigration_desc' },
    'family':             { title: 'legal_asst_family_title',      desc: 'legal_asst_family_desc' },
    'business':           { title: 'legal_asst_business_title',    desc: 'legal_asst_business_desc' },
    'contracts':          { title: 'legal_asst_contracts_title',   desc: 'legal_asst_contracts_desc' },
    'consumer':           { title: 'legal_asst_consumer_title',    desc: 'legal_asst_consumer_desc' },
    'employment':         { title: 'legal_asst_employment_title',  desc: 'legal_asst_employment_desc' },
    'litigation':         { title: 'legal_asst_litigation_title',  desc: 'legal_asst_litigation_desc' },
    'criminal':           { title: 'legal_asst_criminal_title',    desc: 'legal_asst_criminal_desc' },
};

export function getLegalServices(t) {
    return LEGAL_SERVICES.map((service) => {
        const keys = SERVICE_KEY_MAP[service.id];
        return keys
            ? { ...service, title: t[keys.title] || service.title, description: t[keys.desc] || service.description }
            : service;
    });
}

export function getLegalAssistants(t) {
    return LEGAL_ASSISTANTS.map((assistant) => {
        const keys = ASSISTANT_KEY_MAP[assistant.id];
        return keys
            ? { ...assistant, title: t[keys.title] || assistant.title, description: t[keys.desc] || assistant.description }
            : assistant;
    });
}
