/**
 * HTML Sanitization Utility
 * Minimal sanitization for AI-generated websites
 * Security is primarily handled by iframe sandbox attributes
 */

/**
 * Sanitize HTML for safe rendering in iframe previews
 *
 * This performs minimal sanitization since:
 * - The HTML is generated by our own AI system
 * - The iframe has strict sandbox attributes
 * - We only remove dangerous inline event handlers
 *
 * Blocks:
 * - Inline event handlers (onclick, onerror, etc.)
 */
export function sanitizeWebsiteHTML(html: string): string {
  try {
    // Simple regex-based sanitization to remove dangerous event handlers
    // while preserving all CSS and HTML structure
    let sanitized = html;

    // Remove inline event handlers
    const dangerousAttributes = [
      'onclick',
      'ondblclick',
      'onmousedown',
      'onmouseup',
      'onmouseover',
      'onmousemove',
      'onmouseout',
      'onmouseenter',
      'onmouseleave',
      'onload',
      'onunload',
      'onchange',
      'onsubmit',
      'onreset',
      'onselect',
      'onblur',
      'onfocus',
      'onkeydown',
      'onkeypress',
      'onkeyup',
      'onerror',
      'onabort',
    ];

    dangerousAttributes.forEach((attr) => {
      // Remove the attribute and its value
      // Matches: onclick="..." or onclick='...' or onclick=...
      const regex = new RegExp(`\\s*${attr}\\s*=\\s*["'].*?["']`, 'gi');
      sanitized = sanitized.replace(regex, '');

      // Also handle unquoted values
      const regexUnquoted = new RegExp(`\\s*${attr}\\s*=\\s*[^\\s>]+`, 'gi');
      sanitized = sanitized.replace(regexUnquoted, '');
    });

    // Log if anything was changed
    if (html.length !== sanitized.length) {
      console.log('[Sanitize] Removed event handlers:', {
        original: html.length,
        sanitized: sanitized.length,
        removed: html.length - sanitized.length,
      });
    }

    return sanitized;
  } catch (error) {
    console.error('[Sanitize] Failed to sanitize HTML:', error);
    // Return empty safe HTML on error
    return '<!DOCTYPE html><html><head><meta charset="utf-8"><title>Error</title></head><body><p>Failed to load website preview.</p></body></html>';
  }
}

/**
 * Get Content Security Policy for iframe previews
 * Restricts what the iframe can do for additional security
 */
export function getIframeCSP(): string {
  return [
    "default-src 'self'",
    "style-src 'self' 'unsafe-inline'", // Allow inline styles (needed for generated websites)
    "script-src 'self' 'unsafe-inline'", // Allow inline scripts (controlled by sandbox)
    "img-src 'self' data: https:", // Allow images from self, data URIs, and HTTPS
    "font-src 'self' data:", // Allow fonts from self and data URIs
    "connect-src 'self'", // Allow fetch/XHR to same origin only
    "frame-src 'none'", // Prevent nested iframes
    "object-src 'none'", // Block plugins (Flash, Java, etc.)
    "base-uri 'self'", // Restrict base tag
    "form-action 'self'", // Restrict form submissions to same origin
  ].join('; ');
}

/**
 * Get secure sandbox attributes for iframe
 * Provides additional isolation beyond CSP
 */
export function getIframeSandboxAttributes(): string {
  return [
    'allow-same-origin', // Allow access to same-origin resources
    'allow-scripts', // Allow JavaScript (needed for interactive websites)
    'allow-popups', // Allow window.open() for links with target="_blank"
    'allow-forms', // Allow form submission
    'allow-modals', // Allow alert(), confirm(), etc.
  ].join(' ');
}
